#!/usr/bin/env bash
# Vendor-neutral worker launcher. Model syntax belongs to the selected adapter.
set -euo pipefail

usage() { printf 'Usage: %s --role ROLE [--route default|quality-retry] [--adapter FILE] [--selection-output FILE] [--pin FILE] [lifecycle options] --output FILE --error FILE -- worker-arguments...\n' "$0" >&2; }
fail() { printf 'ERROR: %s\n' "$1" >&2; exit "${2:-2}"; }

output_path=''; error_path=''; selection_output_path=''; pin_path=''; adapter_path=''; role=''; route='default'; lifecycle_path=''; attempt=1; mode='unknown'; verification_baseline=''; resource_ledger_path=''; timeout_seconds=0; cancel_file=''; ledger_path=''; assignment_id=''; parent_id=''; resource_id=''
seen_output=false; seen_error=false; seen_role=false; seen_delimiter=false; worker_args=(); required_caps=(); declare -A seen=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --) seen_delimiter=true; shift; worker_args=("$@"); break ;;
    --require-capability) [ "$#" -ge 2 ] || { usage; fail "$1 requires a value"; }; required_caps+=("$2"); shift 2; continue ;;
    --require-capability=*) required_caps+=("${1#*=}"); [ -n "${required_caps[-1]}" ] || fail '--require-capability requires a non-empty value'; shift; continue ;;
    --output|--error|--selection-output|--pin|--adapter|--role|--route|--lifecycle|--attempt|--mode|--verification-baseline|--resource-ledger|--timeout-seconds|--cancel-file|--ledger|--assignment-id|--parent-id|--resource-id)
      option="$1"; [ "$#" -ge 2 ] || { usage; fail "$option requires a value"; }; value="$2"; shift 2 ;;
    --output=*|--error=*|--selection-output=*|--pin=*|--adapter=*|--role=*|--route=*|--lifecycle=*|--attempt=*|--mode=*|--verification-baseline=*|--resource-ledger=*|--timeout-seconds=*|--cancel-file=*|--ledger=*|--assignment-id=*|--parent-id=*|--resource-id=*) option="${1%%=*}"; value="${1#*=}"; [ -n "$value" ] || fail "$option requires a value"; shift ;;
    *) usage; fail "unknown launcher option: $1" ;;
  esac
  case "$option" in
    --output) $seen_output && fail 'duplicate --output option'; output_path="$value"; seen_output=true ;;
    --error) $seen_error && fail 'duplicate --error option'; error_path="$value"; seen_error=true ;;
    --selection-output) [ -n "${seen[selection_output]:-}" ] && fail 'duplicate --selection-output option'; selection_output_path="$value"; seen[selection_output]=1 ;;
    --pin) [ -n "${seen[pin]:-}" ] && fail 'duplicate --pin option'; pin_path="$value"; seen[pin]=1 ;;
    --adapter) [ -n "${seen[adapter]:-}" ] && fail 'duplicate --adapter option'; adapter_path="$value"; seen[adapter]=1 ;;
    --role) $seen_role && fail 'duplicate --role option'; role="$value"; seen_role=true ;;
    --route) [ -n "${seen[route]:-}" ] && fail 'duplicate --route option'; route="$value"; seen[route]=1 ;;
    --lifecycle) [ -n "${seen[lifecycle]:-}" ] && fail 'duplicate --lifecycle option'; lifecycle_path="$value"; seen[lifecycle]=1 ;;
    --attempt) [ -n "${seen[attempt]:-}" ] && fail 'duplicate --attempt option'; attempt="$value"; seen[attempt]=1 ;;
    --mode) [ -n "${seen[mode]:-}" ] && fail 'duplicate --mode option'; mode="$value"; seen[mode]=1 ;;
    --verification-baseline) [ -n "${seen[baseline]:-}" ] && fail 'duplicate --verification-baseline option'; verification_baseline="$value"; seen[baseline]=1 ;;
    --resource-ledger) [ -n "${seen[resource_ledger]:-}" ] && fail 'duplicate --resource-ledger option'; resource_ledger_path="$value"; seen[resource_ledger]=1 ;;
    --timeout-seconds) [ -n "${seen[timeout]:-}" ] && fail 'duplicate --timeout-seconds option'; timeout_seconds="$value"; seen[timeout]=1 ;;
    --cancel-file) [ -n "${seen[cancel]:-}" ] && fail 'duplicate --cancel-file option'; cancel_file="$value"; seen[cancel]=1 ;;
    --ledger) [ -n "${seen[ledger]:-}" ] && fail 'duplicate --ledger option'; ledger_path="$value"; seen[ledger]=1 ;;
    --assignment-id) [ -n "${seen[assignment]:-}" ] && fail 'duplicate --assignment-id option'; assignment_id="$value"; seen[assignment]=1 ;;
    --parent-id) [ -n "${seen[parent]:-}" ] && fail 'duplicate --parent-id option'; parent_id="$value"; seen[parent]=1 ;;
    --resource-id) [ -n "${seen[resource]:-}" ] && fail 'duplicate --resource-id option'; resource_id="$value"; seen[resource]=1 ;;
  esac
done
$seen_delimiter || { usage; fail '-- delimiter is required'; }; $seen_output && [ -n "$output_path" ] || { usage; fail '--output is required'; }; $seen_error && [ -n "$error_path" ] || { usage; fail '--error is required'; }; $seen_role && [ -n "$role" ] || { usage; fail '--role is required'; }; [ "${#worker_args[@]}" -gt 0 ] || { usage; fail 'worker arguments are required after --'; }
case "$route" in default|quality-retry) ;; *) fail "unknown route: '$route'" ;; esac
case "$role" in scout|gate-author|implementer|reviewer|researcher|synthesizer|auditor) ;; *) fail "unknown role: '$role'" ;; esac
[ "${OFFLOAD_WORKER_CONTEXT:-}" = 1 ] && fail 'worker process cannot invoke the launcher; only the orchestrator may create worker processes' 126
for arg in "${worker_args[@]}"; do case "$arg" in --output|--output=*|--model|--model=*|--effort|--effort=*) fail 'caller cannot pass --output, --model, or --effort to the worker' ;; esac; done
case "$timeout_seconds" in ''|*[!0-9]*) fail '--timeout-seconds must be zero or a positive integer' ;; esac
caller_dir="$(pwd -P)"; resolve_path(){ local p="$1" label="$2"; case "$p" in /*) ;; *) p="$caller_dir/$p" ;; esac; mkdir -p "$(dirname "$p")" || fail "could not create $label parent directory"; printf '%s/%s' "$(cd "$(dirname "$p")" && pwd -P)" "$(basename "$p")"; }
output_path="$(resolve_path "$output_path" output)"; error_path="$(resolve_path "$error_path" error)"; [ "$output_path" != "$error_path" ] || fail 'output and error paths must be different'; [ -z "$selection_output_path" ] || selection_output_path="$(resolve_path "$selection_output_path" 'selection output')"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"; repo_root="$(cd "$script_dir/.." && pwd -P)"; policy_file="$repo_root/model-policy.json"; [ -f "$policy_file" ] || fail "model policy file not found at: $policy_file"; jq empty "$policy_file" >/dev/null 2>&1 || fail 'model policy file is not valid JSON'
validation_err=$(jq -r 'if .schema_version != 2 then "schema_version must be integer 2" elif .max_effort != "high" then "max_effort must be high" elif .max_retries_per_worker != 1 then "max_retries_per_worker must be integer 1" elif .quota_action != "handoff" then "quota_action must be handoff" elif ((.roles|type)!="object") then "roles must be an object" elif ([.roles[] | select((.preference|IN("fast","balanced","deep"))|not)]|length)>0 then "role preference is invalid" elif ([.roles[] | select((.effort|IN("low","medium","high"))|not)]|length)>0 then "role effort is invalid" else "" end' "$policy_file"); [ -z "$validation_err" ] || fail "$validation_err"
preference=$(jq -er --arg role "$role" '.roles[$role].preference' "$policy_file") || fail "role not found in policy: $role"; effort=$(jq -er --arg role "$role" '.roles[$role].effort' "$policy_file") || fail "role not found in policy: $role"; required_caps_json=$(jq -c --arg role "$role" '.roles[$role].required_capabilities' "$policy_file");for cap in "${required_caps[@]}"; do required_caps_json=$(jq -c --arg cap "$cap" '.+[$cap]|unique' <<<"$required_caps_json");done
[ "$route" != quality-retry ] || [ -n "$pin_path" ] || fail 'quality-retry requires --pin with the prior selection; use an explicit fallback or handoff when it is unavailable' 3
[ -n "$adapter_path" ] || adapter_path="${OFFLOAD_ADAPTER_BIN:-$script_dir/agy-adapter.sh}"; case "$adapter_path" in /*) ;; *) adapter_path="$caller_dir/$adapter_path" ;; esac; [ -f "$adapter_path" ] || fail "adapter not found: $adapter_path" 127; if [[ "$adapter_path" == *.ps1 ]]; then adapter_cmd=(pwsh -NoProfile -NonInteractive -File "$adapter_path"); else adapter_cmd=("$adapter_path"); fi
request_tmp=$(mktemp);catalog_tmp=$(mktemp);adapter_err_tmp=$(mktemp);selection_tmp=$(mktemp);adapter_out_tmp=$(mktemp);adapter_stderr_tmp=$(mktemp);cleanup(){ rm -f "$request_tmp" "$catalog_tmp" "$adapter_err_tmp" "$selection_tmp" "$adapter_out_tmp" "$adapter_stderr_tmp"; };trap cleanup EXIT
jq -n --arg role "$role" --arg preference "$preference" --arg effort "$effort" --arg revision "$(jq -er '.policy_revision' "$policy_file")" --argjson caps "$required_caps_json" '{protocol_version:1,operation:"catalog",role:$role,preference:$preference,effort:$effort,required_capabilities:$caps,policy_revision:$revision}' >"$request_tmp"
set +e; "${adapter_cmd[@]}" --operation catalog --request "$request_tmp" >"$catalog_tmp" 2>"$adapter_err_tmp"; catalog_code=$?; set -e; [ "$catalog_code" -eq 0 ] || { diagnostic=$(tr '\n' ' ' <"$adapter_err_tmp"); fail "adapter catalog discovery failed with exit code $catalog_code${diagnostic:+: $diagnostic}" 127; }; jq empty "$catalog_tmp" >/dev/null 2>&1 || fail 'adapter catalog is not valid JSON' 127
catalog_adapter=$(jq -er '.adapter|strings|select(length>0)' "$catalog_tmp") || fail 'adapter catalog is missing adapter' 127;catalog_vendor=$(jq -er '.vendor|strings|select(length>0)' "$catalog_tmp") || fail 'adapter catalog is missing vendor' 127;catalog_revision=$(jq -er '.catalog_revision|strings|select(length>0)' "$catalog_tmp") || fail 'adapter catalog is missing catalog_revision' 127;adapter_revision=$(jq -er '.adapter_revision|strings|select(length>0)' "$catalog_tmp") || fail 'adapter catalog is missing adapter_revision' 127;[ "$(jq -er '.protocol_version' "$catalog_tmp")" = 1 ] || fail 'adapter catalog has unsupported protocol_version' 127
selected=$(jq -c --arg pref "$preference" --arg effort "$effort" --argjson caps "$required_caps_json" --arg vendor "$catalog_vendor" '[.models[]? | select((.id|type)=="string" and (.id|length)>0) | select(.available==true and (.quota_available!=false)) | select((.supported_efforts//[])|index($effort)) | select(([$caps[] as $cap | select(((.capabilities//[])|index($cap))==null)]|length)==0) | {model:.,id:.id,vendor:(.vendor//$vendor),score:(((.scores//{})[$pref])//1000000)}] | sort_by(.score,.vendor,.id)|.[0]//empty' "$catalog_tmp") || true; [ -n "$selected" ] || fail "adapter catalog has no eligible model for role '$role', effort '$effort', and required capabilities" 4
selection_reason="catalog selection preference=$preference effort=$effort; filtered unavailable, quota, effort, capability, and static-policy-incompatible candidates";if [ -n "$pin_path" ];then [ -f "$pin_path" ]||fail "pinned selection file not found: $pin_path" 3;pin_adapter=$(jq -er '.adapter//empty' "$pin_path")||fail 'pinned selection is invalid' 3;pin_vendor=$(jq -er '.vendor//empty' "$pin_path")||fail 'pinned selection is missing vendor' 3;pin_id=$(jq -er '.model_id//.model//empty' "$pin_path")||fail 'pinned selection is missing model_id' 3;pin_effort=$(jq -er '.effort//empty' "$pin_path")||fail 'pinned selection is missing effort' 3;[ "$pin_adapter" = "$catalog_adapter" ]&&[ "$pin_vendor" = "$catalog_vendor" ]&&[ "$pin_effort" = "$effort" ]||fail 'pinned selection does not match the current adapter, vendor, or policy effort; explicit fallback or handoff is required' 3;pinned=$(jq -c --arg id "$pin_id" --arg vendor "$pin_vendor" --arg effort "$effort" --argjson caps "$required_caps_json" '[.models[]? | select(.id==$id and ((.vendor// $vendor)==$vendor) and .available==true and (.quota_available!=false) and ((.supported_efforts//[])|index($effort)) and ([$caps[] as $cap|select(((.capabilities//[])|index($cap))==null)]|length)==0)]|.[0]//empty' "$catalog_tmp");[ -n "$pinned" ]||fail "pinned model '$pin_id' is unavailable in catalog revision '$catalog_revision'; explicit fallback or handoff is required" 3;selected=$(jq -c --argjson model "$pinned" --arg id "$pin_id" --arg vendor "$pin_vendor" '{model:$model,id:$id,vendor:$vendor,score:0}' <<<"$selected");selection_reason="pinned selection adapter=$catalog_adapter vendor=$catalog_vendor model_id=$pin_id; catalog_revision=$catalog_revision";fi
jq -n --arg adapter "$catalog_adapter" --arg adapter_revision "$adapter_revision" --arg vendor "$(jq -r '.vendor' <<<"$selected")" --arg model_id "$(jq -r '.id' <<<"$selected")" --arg family_hint "$(jq -r '.model.family_hint // empty' <<<"$selected")" --arg preference "$preference" --arg effort "$effort" --arg catalog_revision "$catalog_revision" --arg policy_revision "$(jq -er '.policy_revision' "$policy_file")" --arg reason "$selection_reason" --arg route "$route" --argjson caps "$required_caps_json" '{protocol_version:1,adapter:$adapter,adapter_revision:$adapter_revision,vendor:$vendor,model_id:$model_id,model:$model_id,family_hint:$family_hint,preference:$preference,effort:$effort,catalog_revision:$catalog_revision,policy_revision:$policy_revision,required_capabilities:$caps,selection_reason:$reason,route:$route}' >"$selection_tmp"; [ -z "$selection_output_path" ] || cp "$selection_tmp" "$selection_output_path"
lifecycle=false; if [ -n "${seen[lifecycle]:-}" ] || [ -n "${seen[attempt]:-}" ] || [ -n "${seen[resource_ledger]:-}" ] || [ -n "${seen[timeout]:-}" ] || [ -n "${seen[cancel]:-}" ]; then lifecycle=true; fi
if ! $lifecycle; then set +e; "${adapter_cmd[@]}" --operation launch --request "$selection_tmp" --output "$output_path" --error "$error_path" -- "${worker_args[@]}" >"$catalog_tmp" 2>"$adapter_err_tmp"; code=$?; set -e; if [ "$code" -ne 0 ] && [ -s "$adapter_err_tmp" ]; then printf 'ERROR: adapter launch failed with exit code %s: %s\n' "$code" "$(tr '\n' ' ' <"$adapter_err_tmp")" >&2; fi; exit "$code"; fi
case "$attempt" in 1|2) ;; *) fail 'attempt must be 1 or 2; policy allows at most one retry per assignment' ;; esac;[ -n "$assignment_id" ]||assignment_id="$role-$(date -u +%Y%m%d%H%M%S)";[ -n "$lifecycle_path" ]||lifecycle_path="$output_path.lifecycle.json";lifecycle_path="$(resolve_path "$lifecycle_path" lifecycle)";[ -z "$resource_ledger_path" ]||resource_ledger_path="$(resolve_path "$resource_ledger_path" 'resource ledger')"
if [ -n "$resource_ledger_path" ];then if [ -f "$resource_ledger_path" ];then ledger_assignment=$(jq -r '.assignment_id' "$resource_ledger_path");ledger_model=$(jq -r '.model' "$resource_ledger_path");ledger_effort=$(jq -r '.effort' "$resource_ledger_path");[ "$ledger_assignment" = "$assignment_id" ]&&[ "$ledger_model" = "$(jq -r '.model_id' "$selection_tmp")" ]&&[ "$ledger_effort" = "$effort" ]||fail 'resource ledger is pinned to a different assignment, model, or effort';[ -n "$verification_baseline" ]||verification_baseline=$(jq -r '.verification_baseline // empty' "$resource_ledger_path");jq -e --argjson attempt "$attempt" '[.attempts[]? | select(.attempt == $attempt)]|length == 0' "$resource_ledger_path" >/dev/null||fail "resource ledger already contains attempt $attempt";else jq -n --arg assignment "$assignment_id" --arg model "$(jq -r '.model_id' "$selection_tmp")" --arg effort "$effort" --arg baseline "${verification_baseline:-}" '{schema_version:1,assignment_id:$assignment,model:$model,effort:$effort,verification_baseline:($baseline|if length>0 then . else null end),attempts:[]}' >"$resource_ledger_path";fi;jq --argjson attempt "$attempt" --arg model "$(jq -r '.model_id' "$selection_tmp")" --arg effort "$effort" --arg baseline "${verification_baseline:-}" --arg lifecycle "$lifecycle_path" '.attempts += [{attempt:$attempt,model:$model,effort:$effort,verification_baseline:($baseline|if length>0 then . else null end),lifecycle:$lifecycle}]' "$resource_ledger_path" >"$resource_ledger_path.tmp";mv -f "$resource_ledger_path.tmp" "$resource_ledger_path";fi
baseline_json=${verification_baseline:+"$verification_baseline"};jq -n --arg assignment "$assignment_id" --argjson attempt "$attempt" --arg role "$role" --arg mode "$mode" --arg policy_revision "$(jq -er '.policy_revision' "$policy_file")" --arg model "$(jq -r '.model_id' "$selection_tmp")" --arg effort "$effort" --arg baseline "${verification_baseline:-}" --arg ledger "${resource_ledger_path:-}" --arg output "$output_path" --arg error "$error_path" --arg lifecycle "$lifecycle_path" '{schema_version:1,assignment_id:$assignment,attempt:$attempt,role:$role,mode:$mode,policy_revision:$policy_revision,model:$model,effort:$effort,verification_baseline:($baseline|if length>0 then . else null end),resource_ledger:($ledger|if length>0 then . else null end),state:"created",events:[],exit_code:null,termination:"none",failure_class:"none",artifacts:{output:$output,error:$error,lifecycle:$lifecycle}}' >"$lifecycle_path"
state(){ local name="$1";jq --arg state "$name" --arg at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" '.events += [{state:$state,at:$at}]|.state=$state' "$lifecycle_path" >"$lifecycle_path.tmp";mv -f "$lifecycle_path.tmp" "$lifecycle_path"; };state created
set +e; "${adapter_cmd[@]}" --operation launch --request "$selection_tmp" --output "$output_path" --error "$error_path" -- "${worker_args[@]}" >"$adapter_out_tmp" 2>"$adapter_stderr_tmp" & adapter_pid=$!;set -e;state started;state running;termination=natural;deadline=0;[ "$timeout_seconds" -gt 0 ]&&deadline=$(( $(date +%s) + timeout_seconds ));while kill -0 "$adapter_pid" 2>/dev/null;do if [ -n "$cancel_file" ]&&[ -f "$cancel_file" ];then termination=canceled;break;fi;if [ "$deadline" -gt 0 ]&&[ "$(date +%s)" -ge "$deadline" ];then termination=timeout;break;fi;sleep 0.05;done;if [ "$termination" != natural ];then kill "$adapter_pid" 2>/dev/null||true;fi;set +e;wait "$adapter_pid";code=$?;set -e
if [ "$termination" = canceled ];then code=130;failure=canceled;terminal_state=canceled;elif [ "$termination" = timeout ];then code=124;failure=timeout;terminal_state=failed;elif [ "$code" -eq 75 ]||grep -Eiq 'quota|resource[_ -]?exhausted|rate limit|\b429\b' "$output_path" "$error_path" 2>/dev/null;then code=75;failure=quota;terminal_state=quota-handoff;elif [ "$code" -eq 0 ]&&jq -e '(.status=="success") and (.structured_output|type=="object")' "$output_path" >/dev/null 2>&1;then code=0;failure=none;terminal_state=completed;else [ "$code" -eq 0 ]&&code=1;failure=malformed_output;terminal_state=failed;fi
jq --arg state "$terminal_state" --arg failure "$failure" --arg termination "$termination" --argjson code "$code" '.exit_code=$code|.failure_class=$failure|.termination=$termination' "$lifecycle_path" >"$lifecycle_path.tmp";mv -f "$lifecycle_path.tmp" "$lifecycle_path";state "$terminal_state";state retained;state cleaned;exit "$code"
