#!/usr/bin/env pwsh
# Select a worker only after adapter preflight establishes access, entitlement,
# capabilities, and capacity for the complete retry budget.
$ErrorActionPreference='Stop'; Set-StrictMode -Version 3.0
function Fail([string]$m,[int]$c=4){[Console]::Error.WriteLine("ERROR: $m");exit $c}
function P($o,[string]$n){if($null -eq $o){return $null};$p=$o.PSObject.Properties[$n];if($null -eq $p){return $null};$p.Value}
function Has($o,[string]$n){$null -ne $o -and $null -ne $o.PSObject.Properties[$n]}
function Text($v){if($null -eq $v){''}else{[string]$v}}
function State($v){(Text $v).Trim().ToLowerInvariant()}
function Safe([string]$v,[int]$max=240){$v=([regex]::Replace((Text $v),'\s+',' ')).Trim();$v=[regex]::Replace($v,'(?i)(token|secret|password|authorization|api[-_]?key)\s*[:=]\s*[^\s,;]+','$1=[redacted]');if($v.Length -gt $max){$v.Substring(0,$max-3)+'...'}else{$v}}
function Obs($p,[string]$n,$fallback,[string]$rn){$v=P $p $n;if($null -eq $v){$v=$fallback};if($null -ne $v){return $v};$r=Safe(P $p $rn);if($r){return [pscustomobject]@{state=Text(P $p "${n}_state");reason=$r}};[pscustomobject]@{}}
function Classify([string]$label,$o){$s=State(P $o 'state');$r=Safe(P $o 'reason');$suffix=if($r){": $r"}else{''};if($s -in @('denied','rejected','unauthenticated','unauthorized','forbidden')){"provider-confirmed $label denied$suffix"}elseif($s -in @('expired','revoked')){"provider-confirmed $label expired$suffix"}elseif($s -eq 'exhausted'){"provider-confirmed $label exhausted$suffix"}elseif($s -eq 'stale'){"$label observation is stale$suffix"}elseif($s -eq 'malformed'){"$label observation is malformed$suffix"}elseif($s -in @('unsupported','unknown','unverified','')){"$label verification is unavailable or unsupported$suffix"}else{''}}
function SafeObs($o){$x=[ordered]@{};foreach($n in @('state','reason','account_ref','billing_route','provider','model','effort')){if(Has $o $n){$v=Text(P $o $n);if($v){$x[$n]=Safe $v}}};$x}
function SafePreflight($p,$a,$e,$b,$m,$f,$u,$scopes){[ordered]@{access=SafeObs $a;account=SafeObs (Obs $p 'account' $a 'account_reason');entitlement=SafeObs $e;billing=SafeObs $b;model=SafeObs $m;effort=SafeObs $f;usage=[ordered]@{state=Safe(P $u 'state');reason=Safe(P $u 'reason');observed_at=Safe(P $u 'observed_at');scopes=@($scopes|ForEach-Object{[ordered]@{scope_id=Safe(Text(P $_ 'scope_id'));remaining_units=P $_ 'remaining_units';reserved_units=P $_ 'reserved_units'}})}}}
function Read-Json([string]$p,[string]$l){try{ConvertFrom-Json -InputObject ([IO.File]::ReadAllText($p)) -Depth 50 -ErrorAction Stop}catch{Fail "$l is not valid JSON: $($_.Exception.Message)" 127}}
$catalogPath='';$policyPath='';$requestPath='';$outputPath='';$pinPath='';$provider='';$allowUnknownUsage=$false;$i=0
while($i -lt $args.Count){$arg=[string]$args[$i];switch($arg){'--catalog'{$i++;$catalogPath=[string]$args[$i]};'--policy'{$i++;$policyPath=[string]$args[$i]};'--request'{$i++;$requestPath=[string]$args[$i]};'--output'{$i++;$outputPath=[string]$args[$i]};'--pin'{$i++;$pinPath=[string]$args[$i]};'--provider'{$i++;$provider=[string]$args[$i]};'--allow-unknown-usage'{$allowUnknownUsage=$true};default{Fail "unknown selector option: $arg" 2}};$i++}
if(-not $catalogPath -or -not $policyPath -or -not $requestPath -or -not $outputPath){Fail '--catalog, --policy, --request, and --output are required' 2}
$catalog=Read-Json $catalogPath 'adapter catalog';$policy=Read-Json $policyPath 'model policy';$request=Read-Json $requestPath 'catalog request';if((P $catalog 'protocol_version') -ne 2){Fail "adapter catalog has unsupported protocol_version '$(P $catalog 'protocol_version')'; protocol version 2 requires verified preflight records" 127}
$adapter=Text(P $catalog 'adapter');$vendor=Text(P $catalog 'vendor');$catalogRevision=Text(P $catalog 'catalog_revision');$adapterRevision=Text(P $catalog 'adapter_revision');if(@($adapter,$vendor,$catalogRevision,$adapterRevision|Where-Object{[string]::IsNullOrWhiteSpace([string]$_)}).Count){Fail 'adapter catalog is missing required metadata' 127}
$pinForEligibility=$null;$pinProviderForEligibility='';if($pinPath){if(-not(Test-Path -LiteralPath $pinPath -PathType Leaf)){Fail "pinned selection file not found: $pinPath" 3};$pinForEligibility=Read-Json $pinPath 'pinned selection';$pinProviderForEligibility=Text(P $pinForEligibility 'provider');if(-not $pinProviderForEligibility){$pinProviderForEligibility=Text(P $pinForEligibility 'vendor')}};$unknownUsageAllowed=$allowUnknownUsage -and (($provider -and $provider.Trim()) -or ($pinPath -and $pinProviderForEligibility))
$estimate=P $policy 'capacity_estimation';$estimateVersion=if(Has $estimate 'version'){[int](P $estimate 'version')}else{1};$assignmentUnits=if(Has $estimate 'assignment_units'){[int](P $estimate 'assignment_units')}else{1};$verificationUnits=if(Has $estimate 'verification_units'){[int](P $estimate 'verification_units')}else{1};$retryUnits=if(Has $estimate 'retry_units'){[int](P $estimate 'retry_units')}else{1};$requiredUnits=$assignmentUnits+$verificationUnits+$retryUnits;$freshness=if(Has $estimate 'usage_freshness_seconds'){[int](P $estimate 'usage_freshness_seconds')}else{300};if($estimateVersion -lt 1 -or $requiredUnits -le 0 -or $freshness -le 0){Fail 'capacity estimation policy is invalid' 127}
$effort=Text(P $request 'effort');$preference=Text(P $request 'preference');$requiredCapabilities=@(P $request 'required_capabilities'|ForEach-Object{Text $_}|Where-Object{$_});$now=[DateTime]::UtcNow;$eligible=[Collections.Generic.List[object]]::new();$rejections=[Collections.Generic.List[string]]::new()
foreach($model in @((P $catalog 'models'))){$id=Text(P $model 'id');$modelProvider=Text(P $model 'provider');if(-not $modelProvider){$modelProvider=if(Has $model 'vendor'){Text(P $model 'vendor')}else{$vendor}};$p=P $model 'preflight';$a=P $p 'access';$e=P $p 'entitlement';$u=P $p 'usage';$account=Obs $p 'account' $a 'account_reason';$billing=Obs $p 'billing' $e 'billing_reason';$providerObs=Obs $p 'provider' $null 'provider_reason';$modelObs=Obs $p 'model' $null 'model_reason';$effortObs=Obs $p 'effort' $null 'effort_reason';$reasons=[Collections.Generic.List[string]]::new();$preflightReasons=[Collections.Generic.List[string]]::new();foreach($pair in @(@('access',$a),@('account',$account),@('entitlement',$e),@('billing',$billing),@('provider',$providerObs),@('model',$modelObs),@('effort',$effortObs))){$rr=Safe(P $pair[1] 'reason');if($rr){$preflightReasons.Add("$($pair[0]) reason: $rr")};$cr=Classify $pair[0] $pair[1];if($cr -and $pair[0] -notin @('access','account','entitlement','billing')){$reasons.Add($cr)}}
if(-not $id){$reasons.Add('missing model id')};if((Has $model 'available') -and (P $model 'available') -eq $false){$reasons.Add('adapter marked model unavailable')};if((Has $model 'quota_available') -and (P $model 'quota_available') -eq $false){$reasons.Add('adapter marked quota unavailable')};$accessState=State(P $a 'state');if($accessState -notin @('verified','authenticated','available')){$cr=Classify 'access' $a;$reasons.Add((if($cr){$cr}else{'access verification is unavailable or unsupported'}))};if(-not(Text(P $account 'account_ref'))){$reasons.Add('account verification is unavailable: account reference was not provided')};$entState=State(P $e 'state');if($entState -notin @('active','continuing')){$cr=Classify 'entitlement' $e;$reasons.Add((if($cr){$cr}else{'entitlement verification is unavailable or unsupported'}))};$billingRoute=Text(P $e 'billing_route');if(-not $billingRoute -or $billingRoute -in @('paid-fallback','unknown')){$cr=Classify 'billing' $billing;$reasons.Add((if($cr){$cr}else{'billing verification is unavailable or unsupported'}))};$supported=@(P $model 'supported_efforts'|ForEach-Object{Text $_});if($supported -notcontains $effort){$s=Safe(P $effortObs 'reason');$reasons.Add((if($s){"effort is unsupported: $s"}else{'effort is unsupported'}))};$caps=@(P $model 'capabilities'|ForEach-Object{Text $_});foreach($cap in $requiredCapabilities){if($caps -notcontains $cap){$reasons.Add("missing capability '$cap'")}}
$observedText=Text(P $u 'observed_at');$observed=$null;if($observedText){try{$observed=[DateTime]::Parse($observedText).ToUniversalTime()}catch{$observed=$null}};$scopes=@(P $u 'scopes');$usageKnown=(State(P $u 'state') -eq 'known' -and $null -ne $observed -and $observed -le $now -and $now.Subtract($observed).TotalSeconds -le $freshness -and $scopes.Count -gt 0);$remaining=[double]::PositiveInfinity;if($usageKnown){foreach($scope in $scopes){if(-not(Has $scope 'remaining_units') -or -not(Has $scope 'reserved_units')){$usageKnown=$false;break};try{$available=[double](P $scope 'remaining_units')-[double](P $scope 'reserved_units');if($available -lt $remaining){$remaining=$available};if($available -lt $requiredUnits){$reasons.Add("insufficient capacity in scope '$(Safe(Text(P $scope 'scope_id')) )'")}}catch{$usageKnown=$false;break}}};$usageState=State(P $u 'state');if($usageState -eq 'exhausted'){$reasons.Add('provider-confirmed usage exhausted')};if(-not $usageKnown -and $usageState -ne 'exhausted'){if($observedText -and $null -eq $observed){$reasons.Add('usage observation is malformed')}elseif($null -ne $observed -and $now.Subtract($observed).TotalSeconds -gt $freshness){$reasons.Add('usage observation is stale')}elseif(-not $unknownUsageAllowed){$reasons.Add('usage verification is unavailable or unsupported')}}
$hasCapacity=@($reasons|Where-Object{$_ -like 'insufficient capacity*'}).Count -gt 0;$blocking=@($reasons|Where-Object{$_ -notlike 'insufficient capacity*'}).Count -gt 0;if(-not $blocking -and -not $hasCapacity -and ($usageKnown -or $unknownUsageAllowed)){$scoreValue=P(P $model 'scores') $preference;if($null -eq $scoreValue){$scoreValue=1000000};try{$score=[double]$scoreValue}catch{$score=1000000};$eligible.Add([pscustomobject]@{Model=$model;Id=$id;Provider=$modelProvider;Score=$score;Remaining=$remaining;UsageKnown=$usageKnown;Preflight=(SafePreflight $p $a $e $billing $modelObs $effortObs $u $scopes);PreflightReasons=@($preflightReasons)})}elseif($reasons.Count){$rejections.Add("${id}: $($reasons -join ', ')")}}
function Diagnostics($items){if($items.Count){'; candidate diagnostics: '+($items -join '; ')}else{''}};if($eligible.Count -eq 0){Fail "no eligible worker: verified access, active entitlement, required capability, and capacity for assignment + verification + one retry are required$(Diagnostics $rejections)" 4}
$selected=$null;if($pinPath){$pin=$pinForEligibility;$pinId=Text(P $pin 'model_id');$pinProvider=$pinProviderForEligibility;if((Text(P $pin 'adapter')) -ne $adapter -or (Text(P $pin 'effort')) -ne $effort -or -not $pinId){Fail 'pinned selection does not match the current adapter or policy effort; explicit fallback or handoff is required' 3};$selected=$eligible|Where-Object{$_.Id -eq $pinId -and $_.Provider -eq $pinProvider}|Select-Object -First 1;if($null -eq $selected){Fail "pinned model '$pinId' is unavailable or no longer eligible; explicit fallback or handoff is required$(Diagnostics $rejections)" 3};$reason="pinned selection adapter=$adapter provider=$($selected.Provider) model_id=$pinId; preflight revalidated"}elseif($provider){$candidates=@($eligible|Where-Object{$_.Provider -eq $provider -or(Text(P $_.Model 'adapter')) -eq $provider -or(Text(P $_.Model 'vendor')) -eq $provider});if(-not $candidates.Count){Fail "explicit provider '$provider' is not eligible; no silent fallback is permitted$(Diagnostics $rejections)" 3};$selected=$candidates|Sort-Object Score,@{Expression={if($null -eq $_.Remaining){-1}else{-[double]$_.Remaining}}},Provider,Id|Select-Object -First 1;$reason="explicit provider '$provider' selected after eligibility checks; no fallback"}else{$selected=$eligible|Sort-Object Score,@{Expression={if($null -eq $_.Remaining){-1}else{-[double]$_.Remaining}}},Provider,Id|Select-Object -First 1;$reason="selected by preference=$preference, capability match, and remaining capacity; estimate units=$requiredUnits (assignment=$assignmentUnits, verification=$verificationUnits, retry=$retryUnits)"}
$usage=P $selected.Preflight 'usage';$selection=[ordered]@{protocol_version=2;adapter=$adapter;adapter_revision=$adapterRevision;vendor=$vendor;provider=$selected.Provider;model_id=$selected.Id;model=$selected.Id;family_hint=Text(P $selected.Model 'family_hint');preference=$preference;effort=$effort;catalog_revision=$catalogRevision;policy_revision=Text(P $policy 'policy_revision');required_capabilities=@($requiredCapabilities);selection_reason=$reason;route=Text(P $request 'route');eligibility='eligible';eligibility_reason='verified access, active entitlement, compatible capabilities, and sufficient capacity';preflight=$selected.Preflight;preflight_reasons=$selected.PreflightReasons;capacity_estimate=[ordered]@{version=$estimateVersion;assignment_units=$assignmentUnits;verification_units=$verificationUnits;retry_units=$retryUnits;required_units=$requiredUnits;freshness_seconds=$freshness};usage_observed_at=Text(P $usage 'observed_at');usage_uncertain=(-not $selected.UsageKnown);reservation=[ordered]@{required_units=$requiredUnits;scopes=@(P $usage 'scopes'|ForEach-Object{Text(P $_ 'scope_id'))}}};$json=$selection|ConvertTo-Json -Depth 50;[IO.File]::WriteAllText([IO.Path]::GetFullPath($outputPath),$json,[Text.Encoding]::UTF8);[Console]::Out.Write($json)
